#数据源配置
#spring:
#  redis:
#    ##redis 单机环境配置
#    host: 127.0.0.1
#    port: 6379
#    password:
#    database: 0
#    ssl: false
#    ##redis 集群环境配置
#    #cluster:
#    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
#    #  commandTimeout: 5000
#  datasource:
#    url: jdbc:mysql://localhost:3306/sp-boot-sever?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    username: root
#    password: wangc951203
#    driver-class-name: com.mysql.cj.jdbc.Driver
#多数据源配置
spring:
  freemarker:
    template-loader-path: classpath:/templates/ # 从类路径加载模板
    charset: UTF-8                              # 模板编码
    check-template-location: true               # 启动时检查模板是否存在
    prefer-file-system-access: false
  redis:
    ##redis 单机环境配置
    ## 本地
    host: 10.5.57.53
    ## 生产
    ##host:
    #redis-3rrsyp.devops.svc
    ## 本地
    port: 31673
    ## 生产
    #port: 6379
    password: KWjsVmuDjj
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    dynamic:
      primary: postgresql #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        #        mysql:
        #          url: jdbc:mysql://10.5.58.132:32000/sp-boot-sever?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
        #          username: root
        #          password: TCIsNRX1pq
        #          driver-class-name: com.mysql.cj.jdbc.Driver https://10.5.67.17/
        postgresql:
          # url: jdbc:postgresql://10.5.56.20:5432/speckle
          url: jdbc:postgresql://10.5.57.168:443/smartlink
          username: smartlink
          password: smartlink-zxgj1234-EWEW4fdnsaj
          #          url: jdbc:postgresql://10.5.58.132:31335/speckle
          #          username: postgres
          #          password: Qing@123
          driver-class-name: org.postgresql.Driver

#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888

#blade配置
blade:
  prop:
    upload-domain: http://localhost:8888
    remote-mode: true
    remote-path: /usr/share/nginx/html
    remote-path-iis: D://iis/html
    log-mode: true

streamFiles:
  url: http://10.5.57.53:30203/minio/speckle-server/upload/
#  url: D:/uploads/streamFiles/

# Minio配置
minio:
  config:
    #    endpoint: http://10.5.57.53:30203
    ip: 10.5.57.168 #ip地址
    port: 9000  #  端口号
    accessKey: openpitrixminioaccesskey #  账号
    secretKey: openpitrixminiosecretkey #  密码
    secure: false #如果是true，则用的是https而不是http,默认值是true
    bucketName: "stream-files-uploads"  # 桶的名字
    folderName: "uploads" #文件夹名
    downloadDir: "/uploads/streamFiles/"  #保存到本地的路径

#oss配置
oss:
  enabled: true
  name: minio
  tenant-mode: false
  endpoint: http://minio:9000
  access-key: openpitrixminioaccesskey
  secret-key: openpitrixminiosecretkey
  bucket-name: speckle-server

#加密言
server:
  port: 8080
smartlink:
  token_url: http://10.5.57.168:3000/auth/token
  auth_local_login_url: http://10.5.57.168:3000/auth/local/login?challenge=
  register_url: http://10.5.57.168:3000/auth/local/register